name: Build Soza iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Download project
        uses: actions/checkout@v5

      - name: Build Soza
        run: |
          xcodebuild \
            -project SozaBrowser.xcodeproj \
            -scheme SozaBrowser \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Make IPA
        run: |
          mkdir Payload
          cp -R build/Build/Products/Release-iphoneos/SozaBrowser.app Payload/
          zip -r SozaBrowser.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SozaBrowser-iOS
          path: SozaBrowser.ipa
