name: Build Soza iOS

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Download project
        uses: actions/checkout@v5

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Show project schemes
        run: |
          xcodebuild \
            -project SozaBrowser.xcodeproj \
            -list

      - name: Build Soza
        run: |
          xcodebuild \
            -project SozaBrowser.xcodeproj \
            -scheme SozaBrowser \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            build
